import time
import json
from app.core.database import supabase
from app.services.portfolio_service import update_portfolio_on_trade
import _nanotrade_ext

async def place_order(
    user_id: str,
    is_user: bool,
    side: str,
    price: float,
    quantity: int,
    engine: _nanotrade_ext.MatchingEngine,
    redis_client
) -> dict:
    """
    Submits a limit order into the matching engine.
    Persists the order, matched trades, updates portfolios, and publishes updates to Redis.
    """
    # 1. Insert order into database to get a unique integer order ID
    order_db_resp = supabase.table("orders").insert({
        "user_id": user_id,
        "side": side,
        "price": price,
        "quantity": quantity,
        "status": "NEW"
    }).execute()
    
    if not order_db_resp.data:
        raise Exception("Failed to insert order into database")
        
    order_id = order_db_resp.data[0]["id"]
    
    # 2. Create C++ Order object
    order_type = _nanotrade_ext.OrderType.BUY if side == "BUY" else _nanotrade_ext.OrderType.SELL
    cpp_order = _nanotrade_ext.Order(
        order_id,
        order_type,
        float(price),
        quantity,
        int(time.time()),
        user_id,
        is_user
    )
    
    # 3. Process order in-process via C++ engine
    result = engine.process_order(cpp_order)
    
    # 4. Handle trades generated by engine matching
    trades_list = []
    for t in result.trades:
        # Insert trade record into Supabase
        trade_db_resp = supabase.table("trades").insert({
            "buyer_id": t.buyer_id,
            "seller_id": t.seller_id,
            "price": t.price,
            "quantity": t.quantity,
            "timestamp": t.timestamp
        }).execute()
        
        # Deduct traded quantity from the order that was matched against in the database
        matched_order_id = t.sell_order_id if side == "BUY" else t.buy_order_id
        matched_order_db = supabase.table("orders").select("quantity").eq("id", matched_order_id).execute().data
        if matched_order_db:
            matched_qty = matched_order_db[0]["quantity"]
            new_matched_qty = max(0, matched_qty - t.quantity)
            new_matched_status = "FILLED" if new_matched_qty == 0 else "PARTIAL"
            supabase.table("orders").update({
                "quantity": new_matched_qty,
                "status": new_matched_status
            }).eq("id", matched_order_id).execute()
            
        # Update user profiles and portfolios (USDT balance, BTC holdings)
        await update_portfolio_on_trade(t.buyer_id, t.seller_id, t.price, t.quantity)
        
        # Format trade dictionary
        trade_dict = {
            "buyOrderId": t.buy_order_id,
            "sellOrderId": t.sell_order_id,
            "price": t.price,
            "quantity": t.quantity,
            "timestamp": t.timestamp,
            "buyer_id": t.buyer_id,
            "seller_id": t.seller_id
        }
        trades_list.append(trade_dict)
        
        # Publish trade to Redis pub/sub channel
        await redis_client.publish("trades", json.dumps(trade_dict))
        
    # 5. Update the placed order's remaining quantity and status
    supabase.table("orders").update({
        "quantity": result.remaining_quantity,
        "status": result.fill_status
    }).eq("id", order_id).execute()
    
    # 6. Publish updated C++ orderbook depth to Redis
    orderbook_data = engine.get_order_book()
    await redis_client.publish("orderbook", orderbook_data)
    
    return {
        "order_id": order_id,
        "status": result.fill_status,
        "remaining_quantity": result.remaining_quantity,
        "trades": trades_list
    }
