import time
import json
import uuid
from datetime import datetime, timezone
from app.core.database import supabase
from app.services.portfolio_service import update_portfolio_on_trade, validate_user_funds, is_valid_uuid, get_portfolio_data
from app.api.deps import get_user_lock
import _nanotrade_ext

async def place_order(
    user_id: str,
    is_user: bool,
    side: str,
    price: float,
    quantity: float,
    engine: _nanotrade_ext.MatchingEngine,
    redis_client
) -> dict:
    """
    Submits a limit order into the matching engine.
    Locks execution on a per-user basis (if real user and not system bot) to serialize validation and engine execution.
    Persists the order, matched trades, updates portfolios, and publishes updates to Redis.
    """
    order_id = str(uuid.uuid4())

    if is_valid_uuid(user_id) and user_id != "00000000-0000-0000-0000-000000000000":
        # Serialize processing for real users using async lock to prevent double-spending/race conditions
        async with get_user_lock(user_id):
            # Pre-execution validation
            await validate_user_funds(user_id, side, price, quantity)
            return await _process_order_internal(
                order_id=order_id,
                user_id=user_id,
                is_user=is_user,
                side=side,
                price=price,
                quantity=quantity,
                engine=engine,
                redis_client=redis_client
            )
    else:
        # Simulator bots or invalid UUIDs bypass lock and funds check
        return await _process_order_internal(
            order_id=order_id,
            user_id=user_id,
            is_user=is_user,
            side=side,
            price=price,
            quantity=quantity,
            engine=engine,
            redis_client=redis_client
        )

async def _process_order_internal(
    order_id: str,
    user_id: str,
    is_user: bool,
    side: str,
    price: float,
    quantity: float,
    engine: _nanotrade_ext.MatchingEngine,
    redis_client
) -> dict:
    timestamp_ms = int(time.time() * 1000)
    created_at_iso = datetime.now(timezone.utc).isoformat()
    
    # Determine bot attributes
    is_bot = (user_id == "00000000-0000-0000-0000-000000000000")
    source = "simulator" if is_bot else "user"

    # 1. Insert order into database
    order_db_resp = supabase.table("orders").insert({
        "id": order_id,
        "user_id": user_id,
        "side": side,
        "price": price,
        "quantity": quantity,  # Keep unscaled float in database
        "status": "NEW",
        "is_bot": is_bot,
        "source": source,
        "created_at": created_at_iso
    }).execute()
    
    if not order_db_resp.data:
        raise Exception("Failed to insert order into database")
        
    # 2. Scale quantity for C++ Matching Engine (1 BTC = 1,000,000 engine units)
    cpp_quantity = int(quantity * 1_000_000)
    
    # 3. Create C++ Order object
    order_type = _nanotrade_ext.OrderType.BUY if side == "BUY" else _nanotrade_ext.OrderType.SELL
    cpp_order = _nanotrade_ext.Order(
        order_id,
        order_type,
        float(price),
        cpp_quantity,
        timestamp_ms,
        user_id,
        is_user
    )
    
    # 4. Process order in-process via C++ engine
    result = engine.process_order(cpp_order)
    
    # 5. Handle trades generated by engine matching
    trades_list = []
    for t in result.trades:
        unscaled_trade_qty = t.quantity / 1_000_000
        
        # Check if either buyer or seller is bot
        is_bot_trade = (t.buyer_id == "00000000-0000-0000-0000-000000000000" or 
                        t.seller_id == "00000000-0000-0000-0000-000000000000")
        trade_created_at = datetime.fromtimestamp(t.timestamp / 1000.0, tz=timezone.utc).isoformat()
        
        # Insert trade record into Supabase
        supabase.table("trades").insert({
            "id": t.trade_id,
            "buyer_id": t.buyer_id,
            "seller_id": t.seller_id,
            "price": t.price,
            "quantity": unscaled_trade_qty,
            "is_bot_trade": is_bot_trade,
            "created_at": trade_created_at
        }).execute()
        
        # Deduct traded quantity from the order that was matched against in the database
        matched_order_id = t.sell_order_id if side == "BUY" else t.buy_order_id
        matched_order_db = supabase.table("orders").select("quantity").eq("id", matched_order_id).execute().data
        if matched_order_db:
            matched_qty = float(matched_order_db[0]["quantity"])
            new_matched_qty = max(0.0, matched_qty - unscaled_trade_qty)
            new_matched_status = "FILLED" if new_matched_qty < 1e-6 else "PARTIALLY_FILLED"
            supabase.table("orders").update({
                "quantity": new_matched_qty,
                "status": new_matched_status
            }).eq("id", matched_order_id).execute()
            
        # Update user profiles and portfolios (USDT balance, BTC holdings)
        await update_portfolio_on_trade(t.buyer_id, t.seller_id, t.price, unscaled_trade_qty)
        
        # Format trade dictionary for JSON response/publication
        trade_dict = {
            "trade_id": t.trade_id,
            "buy_order_id": t.buy_order_id,
            "sell_order_id": t.sell_order_id,
            "price": t.price,
            "quantity": unscaled_trade_qty,
            "timestamp": t.timestamp,
            "buyer_id": t.buyer_id,
            "seller_id": t.seller_id
        }
        trades_list.append(trade_dict)
        
        # Publish standardized trade event to Redis
        trade_event = {
            "type": "trade",
            "data": trade_dict,
            "timestamp": timestamp_ms
        }
        await redis_client.publish("trade", json.dumps(trade_event))
        
        # Publish user_update events for both parties (if real users)
        if is_valid_uuid(t.buyer_id) and t.buyer_id != "00000000-0000-0000-0000-000000000000":
            buyer_portfolio = await get_portfolio_data(t.buyer_id)
            await redis_client.publish("user_update", json.dumps({
                "type": "user_update",
                "data": buyer_portfolio,
                "timestamp": timestamp_ms
            }))
        if is_valid_uuid(t.seller_id) and t.seller_id != "00000000-0000-0000-0000-000000000000":
            seller_portfolio = await get_portfolio_data(t.seller_id)
            await redis_client.publish("user_update", json.dumps({
                "type": "user_update",
                "data": seller_portfolio,
                "timestamp": timestamp_ms
            }))
            
    # 6. Update the placed order's remaining quantity and status
    unscaled_rem_qty = result.remaining_quantity / 1_000_000
    supabase.table("orders").update({
        "quantity": unscaled_rem_qty,
        "status": result.fill_status
    }).eq("id", order_id).execute()
    
    # 7. Publish updated C++ orderbook depth to Redis
    orderbook_data = engine.get_order_book()
    try:
        parsed_orderbook = json.loads(orderbook_data)
        if isinstance(parsed_orderbook, dict):
            for side_name in ["bids", "asks"]:
                if side_name in parsed_orderbook:
                    for entry in parsed_orderbook[side_name]:
                        if "quantity" in entry:
                            entry["quantity"] = entry["quantity"] / 1_000_000
    except Exception:
        parsed_orderbook = orderbook_data
        
    orderbook_event = {
        "type": "orderbook",
        "data": parsed_orderbook,
        "timestamp": timestamp_ms
    }
    await redis_client.publish("orderbook", json.dumps(orderbook_event))
    
    # Cache the engine's last traded price in Redis
    last_price = engine.get_last_traded_price()
    if last_price > 0.0:
        await redis_client.set("last_traded_price", str(last_price))
        # Publish a price event
        price_event = {
            "type": "price",
            "data": {"last_traded_price": last_price},
            "timestamp": timestamp_ms
        }
        await redis_client.publish("price", json.dumps(price_event))
    
    return {
        "order_id": order_id,
        "status": result.fill_status,
        "remaining_quantity": unscaled_rem_qty,
        "trades": trades_list
    }
